### ISSUE TITLE
Unable to look up library

### ISSUE THREAD

**Issue by Trevorlg** [namahu/clickupForGoogleAppsScript#20]
Via Google Sheets >> Apps Script >> Add a Library

Script ID: MWpr83H8HSn9MP0szQUnM8zG9S3INQskC

Unable to look up library. Check the ID and access permissions and try again.

**Comment by namahu** [comment]
@Trevorlg 

Thank you for contacting me.
I had put "Project ID" in the way to add libraries, so I changed it to "Script ID".

**Comment by Trevorlg** [comment]
Yup, works to add the library now
:+1:
